"""
Questionnaire definitions registry — Python mirror of the frontend fixture.
Used by questionnaire_enrichment.py to transform raw answers into structured clinical documents.

Must stay in sync with: frontend_mvp/src/fixtures/symptomQuestionnaire.js
"""

# Frequency options shared across many sections
FREQUENCY_OPTIONS = {
    "none": "None",
    "1-2": "1-2 times",
    "3-4": "3-4 times",
    "5-6": "5-6 times",
    "6+": "6+ times",
}

FREQUENCY_SEVERITY_MAP = {
    "none": 0,
    "1-2": 1,
    "3-4": 2,
    "5-6": 3,
    "6+": 4,
}

BODY_REGION_COUNT_SEVERITY_MAP = [
    # (threshold, severity)
    (0, 0),
    (1, 1),
    (3, 2),
    (6, 3),
    (10, 4),
]


def region_count_to_severity(count):
    """Map body region selection count to a 0-4 severity score."""
    severity = 0
    for threshold, score in BODY_REGION_COUNT_SEVERITY_MAP:
        if count >= threshold:
            severity = score
    return severity


SECTIONS = [
    {
        "id": "SN001",
        "title": "Appetite Loss",
        "clinical_area": "nutrition",
        "severity_source": "appetite_rating",
        "questions": [
            {
                "id": "appetite_rating",
                "type": "rating",
                "text": "How is your appetite on a scale of one to five?",
                "options": {
                    1: "Very good",
                    2: "Good",
                    3: "Normal",
                    4: "Poor",
                    5: "Very poor",
                },
                "min": 1,
                "max": 5,
                "severity_direction": "ascending",
                "required": True,
            },
            {
                "id": "appetite_causes",
                "type": "multi-select",
                "text": "What led to your poor appetite? (Choose all that apply)",
                "options": {
                    "nausea": "Nausea and vomiting",
                    "mouth_sores": "Mouth sores",
                    "swallowing": "Swallowing difficulties",
                    "taste": "Taste changes",
                    "fullness": "Feeling of fullness",
                    "mood": "Low mood / Lost interest in taking food and drinks",
                    "others": "Others, please specify",
                },
                "conditional": {"depends_on": "appetite_rating", "operator": "gte", "value": 4},
                "required": False,
            },
        ],
    },
    {
        "id": "SN002",
        "title": "Constipation/Diarrhoea",
        "clinical_area": "gastrointestinal",
        "severity_source": "bowel_frequency",
        "severity_method": "frequency_map",
        "questions": [
            {
                "id": "bowel_frequency",
                "type": "single-select",
                "text": "How many times have you had bowel opening since the last record?",
                "options": FREQUENCY_OPTIONS,
                "required": True,
            },
            {
                "id": "bowel_description",
                "type": "multi-select",
                "text": "How would you describe it/them? (Choose all that apply)",
                "options": {
                    "constipation": "Constipation",
                    "diarrhoea": "Diarrhoea",
                    "normal": "Normal",
                },
                "conditional": {"depends_on": "bowel_frequency", "operator": "not_eq", "value": "none"},
                "required": False,
            },
            {
                "id": "stool_appearance",
                "type": "color-chart",
                "text": "Which of the following has the closest resemblance to the shape of your faeces?",
                "options": {
                    "small_pebbles": "Small pebbles",
                    "black_tarry": "Black and tarry",
                    "mushy_ragged": "Mushy with ragged edges",
                    "lumpy_sausage": "Lumpy and sausage-like",
                    "sausage_cracks": "Sausage-shape with cracks on surface",
                    "smooth_sausage": "Smooth, soft sausage-shape",
                    "soft_blobs": "Soft blobs with clear cut edges",
                    "liquid": "Liquid consistency with no solid pieces",
                    "others_specify": "Other – please specify",
                },
                "alert_values": ["black_tarry"],
                "conditional": {"depends_on": "bowel_frequency", "operator": "in_list", "value": ["3-4", "5-6", "6+"]},
                "required": False,
            },
            {
                "id": "stool_appearance_other_text",
                "type": "text",
                "text": "Please specify:",
                "placeholder": "Describe the appearance...",
                "conditional": {"depends_on": "stool_appearance", "operator": "contains", "value": "others_specify"},
                "required": False,
            },
        ],
    },
    {
        "id": "SN003",
        "title": "Cough",
        "clinical_area": "respiratory",
        "severity_source": "cough_pain",
        "severity_fallback": "cough_frequency",
        "severity_fallback_method": "frequency_map",
        "questions": [
            {
                "id": "cough_frequency",
                "type": "single-select",
                "text": "How frequent is the coughing?",
                "options": FREQUENCY_OPTIONS,
                "required": True,
            },
            {
                "id": "cough_pain",
                "type": "rating",
                "text": "How would you describe the pain in your chest when you cough? Rate it on a scale of one to five.",
                "options": {
                    0: "None",
                    1: "Very mild",
                    2: "Mild",
                    3: "Moderate",
                    4: "Bad",
                    5: "Very bad",
                },
                "min": 0,
                "max": 5,
                "severity_direction": "ascending",
                "conditional": {"depends_on": "cough_frequency", "operator": "not_eq", "value": "none"},
                "required": False,
            },
            {
                "id": "cough_type",
                "type": "single-select",
                "text": "Is your cough mostly dry or wet cough?",
                "options": {
                    "dry": "Dry",
                    "wet": "Wet",
                },
                "conditional": {"depends_on": "cough_frequency", "operator": "in_list", "value": ["3-4", "5-6", "6+"]},
                "required": False,
            },
            {
                "id": "phlegm_color",
                "type": "color-chart",
                "text": "What is the colour of your phlegm?",
                "options": {
                    "transparent": "Transparent",
                    "white": "White",
                    "yellow": "Yellow",
                    "green": "Green",
                    "red": "Red",
                    "brown": "Brown",
                    "black": "Black",
                },
                "alert_values": ["red", "black"],
                "conditional": {"depends_on": "cough_type", "operator": "eq", "value": "wet"},
                "required": False,
            },
        ],
    },
    {
        "id": "SN004",
        "title": "Dyspnea",
        "clinical_area": "respiratory",
        "severity_source": "dyspnea_pain",
        "questions": [
            {
                "id": "dyspnea_frequency",
                "type": "single-select",
                "text": "How often did you experience shortness of breath?",
                "options": FREQUENCY_OPTIONS,
                "required": True,
            },
            {
                "id": "dyspnea_pain",
                "type": "rating",
                "text": "How would you describe the pain when you are short of breath? Rate it on a scale of one to five.",
                "options": {
                    0: "None",
                    1: "Very mild",
                    2: "Mild",
                    3: "Moderate",
                    4: "Bad",
                    5: "Very bad",
                },
                "min": 0,
                "max": 5,
                "severity_direction": "ascending",
                "required": True,
            },
            {
                "id": "dyspnea_activities",
                "type": "multi-select",
                "text": "What activities usually cause shortness of breath? (Choose all that apply)",
                "options": {
                    "talking": "Talking",
                    "standing": "Standing",
                    "running": "Running",
                    "getting_up": "Getting out of bed",
                    "stairs": "Walking up the stairs",
                    "walking": "Walking short distances",
                    "others": "Others, please specify",
                },
                "conditional": {"depends_on": "dyspnea_frequency", "operator": "in_list", "value": ["3-4", "5-6", "6+"]},
                "required": False,
            },
        ],
    },
    {
        "id": "SN005",
        "title": "Dysuria",
        "clinical_area": "urological",
        "severity_source": "dysuria_severity",
        "questions": [
            {
                "id": "dysuria_frequency",
                "type": "single-select",
                "text": "How often did you have difficulty urinating since the last record?",
                "options": FREQUENCY_OPTIONS,
                "required": True,
            },
            {
                "id": "dysuria_severity",
                "type": "rating",
                "text": "To what extent does it affect you? Rate it on a scale of one to five.",
                "options": {
                    1: "Very mild",
                    2: "Mild",
                    3: "Moderate",
                    4: "Bad",
                    5: "Very bad",
                },
                "min": 1,
                "max": 5,
                "severity_direction": "ascending",
                "required": True,
            },
            {
                "id": "dysuria_location",
                "type": "multi-select",
                "text": "Where do you feel pain/a burning sensation when you urinate? (Choose all that apply)",
                "options": {
                    "bladder": "Bladder",
                    "prostate": "Prostate",
                    "urethra": "Urethra",
                    "others": "Others, please specify",
                },
                "conditional": {"depends_on": "dysuria_frequency", "operator": "in_list", "value": ["3-4", "5-6", "6+"]},
                "required": False,
            },
            {
                "id": "urine_color",
                "type": "color-chart",
                "text": "Which of the following has the closest resemblance to the colour of your urine?",
                "options": {
                    "transparent": "Transparent",
                    "yellow": "Yellow",
                    "orange": "Orange",
                    "red": "Red",
                    "brown": "Brown",
                    "blue_green": "Blue green",
                },
                "alert_values": ["red", "brown"],
                "conditional": {"depends_on": "dysuria_frequency", "operator": "in_list", "value": ["3-4", "5-6", "6+"]},
                "required": False,
            },
        ],
    },
    {
        "id": "SN006",
        "title": "Insomnia",
        "clinical_area": "sleep",
        "severity_source": "sleep_quality",
        "questions": [
            {
                "id": "sleep_quality",
                "type": "rating",
                "text": "How would you rate the quality of sleep last night? Rate it on a scale of one to five.",
                "options": {
                    1: "Very good",
                    2: "Good",
                    3: "Normal",
                    4: "Poor",
                    5: "Very poor",
                },
                "min": 1,
                "max": 5,
                "severity_direction": "ascending",
                "required": True,
            },
            {
                "id": "sleep_hours",
                "type": "slider",
                "text": "Around how many hours have you slept last night in total?",
                "slider_config": {"min": 0.5, "max": 9.5, "step": 0.5, "unit": " hours", "min_label": "Less than 1 hour", "max_label": "More than 9 hours"},
                "alert_rule": {"operator": "lte", "value": 3},
                "conditional": {"depends_on": "sleep_quality", "operator": "gte", "value": 4},
                "required": False,
            },
            {
                "id": "sleep_symptoms",
                "type": "multi-select",
                "text": "Have these symptoms affected your quality of sleep? (Choose all that apply)",
                "options": {
                    "not_applicable": "Not applicable",
                    "muscle_pain": "Muscle pain",
                    "joint_pain": "Joint pain",
                    "sore_throat": "Sore throat",
                    "headaches": "Headaches",
                    "anxiety": "Feeling anxious and/or depressed",
                    "memory": "Memory or concentration problems",
                    "exhausted": "Exhausted by everyday tasks",
                    "others_specify": "Other – please specify",
                },
                "exclusive_options": ["not_applicable"],
                "conditional": {"depends_on": "sleep_quality", "operator": "gte", "value": 4},
                "required": False,
            },
            {
                "id": "sleep_symptoms_other_text",
                "type": "text",
                "text": "Please specify:",
                "placeholder": "Describe your symptom...",
                "conditional": {"depends_on": "sleep_symptoms", "operator": "contains", "value": "others_specify"},
                "required": False,
            },
        ],
    },
    {
        "id": "SN007",
        "title": "Fatigue",
        "clinical_area": "energy",
        "severity_source": "fatigue_level",
        "questions": [
            {
                "id": "fatigue_level",
                "type": "rating",
                "text": "How is the general level of fatigue during the past 24 hours? Rate it on a scale of one to five.",
                "options": {
                    0: "None",
                    1: "Very mild",
                    2: "Mild",
                    3: "Moderate",
                    4: "Bad",
                    5: "Very bad",
                },
                "min": 0,
                "max": 5,
                "severity_direction": "ascending",
                "required": True,
            },
            {
                "id": "fatigue_interference",
                "type": "rating",
                "text": "How has fatigue interfered with your general activity? Rate it on a scale of one to five.",
                "options": {
                    0: "None",
                    1: "Very mild",
                    2: "Mild",
                    3: "Moderate",
                    4: "Bad",
                    5: "Very bad",
                },
                "min": 0,
                "max": 5,
                "severity_direction": "ascending",
                "conditional": {"depends_on": "fatigue_level", "operator": "gte", "value": 2},
                "required": False,
            },
        ],
    },
    {
        "id": "SN008",
        "title": "Nausea/Vomiting",
        "clinical_area": "gastrointestinal",
        "severity_source": "nausea_level",
        "questions": [
            {
                "id": "nausea_level",
                "type": "rating",
                "text": "How would you describe your nausea? Rate it on a scale of one to five.",
                "options": {
                    0: "None",
                    1: "Very mild",
                    2: "Mild",
                    3: "Moderate",
                    4: "Bad",
                    5: "Very bad",
                },
                "min": 0,
                "max": 5,
                "severity_direction": "ascending",
                "required": True,
            },
            {
                "id": "vomiting_episodes",
                "type": "single-select",
                "text": "How many episodes of vomiting occurred since the last record?",
                "options": FREQUENCY_OPTIONS,
                "required": True,
            },
            {
                "id": "vomit_color",
                "type": "color-chart",
                "text": "What was the colour of the vomit?",
                "options": {
                    "white": "White",
                    "foamy": "Foamy",
                    "green": "Green",
                    "yellow": "Yellow",
                    "orange": "Orange",
                    "pink": "Pink",
                    "red": "Red",
                    "bloody": "Bloody",
                    "brown": "Brown",
                    "black": "Black",
                },
                "alert_values": ["red", "bloody", "black"],
                "conditional": {"depends_on": "vomiting_episodes", "operator": "not_eq", "value": "none"},
                "required": False,
            },
        ],
    },
    {
        "id": "SN009",
        "title": "Hot Flashes",
        "clinical_area": "thermoregulation",
        "severity_source": "hot_flash_intensity",
        "questions": [
            {
                "id": "hot_flash_frequency",
                "type": "single-select",
                "text": "How many times have you experienced hot flashes since the last record?",
                "options": FREQUENCY_OPTIONS,
                "required": True,
            },
            {
                "id": "hot_flash_intensity",
                "type": "rating",
                "text": "How intense are your hot flashes? Rate it on a scale of one to five.",
                "options": {
                    1: "Very mild",
                    2: "Mild",
                    3: "Moderate",
                    4: "Bad",
                    5: "Very bad",
                },
                "min": 1,
                "max": 5,
                "severity_direction": "ascending",
                "required": True,
            },
            {
                "id": "hot_flash_duration",
                "type": "slider",
                "text": "How long do they last?",
                "slider_config": {"min": 0, "max": 15, "step": 1, "unit": " minutes", "max_label": "15+ min"},
                "conditional": {"depends_on": "hot_flash_frequency", "operator": "in_list", "value": ["3-4", "5-6", "6+"]},
                "required": False,
            },
            {
                "id": "hot_flash_symptoms",
                "type": "multi-select",
                "text": "Do they come with the following symptoms? (Choose all that apply)",
                "options": {
                    "not_applicable": "Not applicable",
                    "palpitations": "Palpitations (Rapid heartbeat)",
                    "sweating": "Sweating",
                    "nausea": "Nausea",
                    "dizziness": "Dizziness",
                    "anxiety": "Anxiety",
                    "headache": "Headache",
                    "weakness": "Weakness",
                    "suffocation": "Feeling of suffocation",
                    "chills": "Followed by chills",
                    "others_specify": "Other – please specify",
                },
                "exclusive_options": ["not_applicable"],
                "conditional": {"depends_on": "hot_flash_frequency", "operator": "in_list", "value": ["3-4", "5-6", "6+"]},
                "required": False,
            },
            {
                "id": "hot_flash_symptoms_other_text",
                "type": "text",
                "text": "Please specify:",
                "placeholder": "Describe your symptom...",
                "conditional": {"depends_on": "hot_flash_symptoms", "operator": "contains", "value": "others_specify"},
                "required": False,
            },
        ],
    },
    {
        "id": "SN010",
        "title": "Vaginal Condition",
        "clinical_area": "gynecological",
        "severity_source": "vaginal_discomfort",
        "questions": [
            {
                "id": "vaginal_discharge",
                "type": "single-select",
                "text": "Did you notice any vaginal discharge since the last record?",
                "options": {
                    "yes": "Yes",
                    "no": "No",
                    "dry": "No and it feels dry",
                },
                "required": True,
            },
            {
                "id": "vaginal_discomfort",
                "type": "rating",
                "text": "How would you describe your vaginal discomfort? Rate it on a scale of one to five.",
                "options": {
                    0: "None",
                    1: "Very mild",
                    2: "Mild",
                    3: "Moderate",
                    4: "Bad",
                    5: "Very bad",
                },
                "min": 0,
                "max": 5,
                "severity_direction": "ascending",
                "required": True,
            },
            {
                "id": "discharge_color",
                "type": "color-chart",
                "text": "How would you describe the colour of the discharge(s)?",
                "options": {
                    "clear": "Clear",
                    "white": "White",
                    "opaque": "Opaque in Colour",
                    "yellowish": "Yellowish",
                    "cottage_cheese": "Cottage-cheese like",
                    "bloody": "Bloody",
                },
                "alert_values": ["bloody"],
                "conditional": {"depends_on": "vaginal_discharge", "operator": "in_list", "value": ["yes", "dry"]},
                "required": False,
            },
        ],
    },
    {
        "id": "SN011",
        "title": "Headaches",
        "clinical_area": "neurological",
        "severity_source": "headache_severity",
        "questions": [
            {
                "id": "headache_frequency",
                "type": "single-select",
                "text": "How many headaches did you experience since the last record?",
                "options": FREQUENCY_OPTIONS,
                "required": True,
            },
            {
                "id": "headache_severity",
                "type": "rating",
                "text": "How would you rate your headaches? Rate it on a scale of one to five.",
                "options": {
                    1: "Very mild",
                    2: "Mild",
                    3: "Moderate",
                    4: "Bad",
                    5: "Very bad",
                },
                "min": 1,
                "max": 5,
                "severity_direction": "ascending",
                "required": True,
            },
            {
                "id": "headache_location",
                "type": "body-diagram",
                "text": "Where were your headaches located?",
                "regions": {
                    "right_head": "Right side of head",
                    "left_head": "Left side of head",
                    "back_head": "Back of head",
                    "left_temple": "Left temple",
                    "right_temple": "Right temple",
                    "behind_eyes": "Between eyes",
                    "forehead": "Forehead",
                    "top_head": "Top of head",
                },
                "conditional": {"depends_on": "headache_frequency", "operator": "in_list", "value": ["3-4", "5-6", "6+"]},
                "required": False,
            },
        ],
    },
    {
        "id": "SN012",
        "title": "Joint Pain",
        "clinical_area": "musculoskeletal",
        "severity_source": "joint_pain_areas",
        "severity_method": "region_count",
        "questions": [
            {
                "id": "joint_pain_areas",
                "type": "body-diagram",
                "text": "Please choose all the areas where you have experienced joint pain since the last record.",
                "regions": {
                    "left_shoulder": "Left shoulder girdle",
                    "right_shoulder": "Right shoulder girdle",
                    "left_elbow": "Left elbow",
                    "right_elbow": "Right elbow",
                    "left_wrist": "Left wrist",
                    "right_wrist": "Right wrist",
                    "left_fingers": "Fingers on left hand",
                    "right_fingers": "Fingers on right hand",
                    "upper_back": "Upper back",
                    "lower_back": "Lower back",
                    "left_hip": "Left hip",
                    "right_hip": "Right hip",
                    "left_knee": "Left knee",
                    "right_knee": "Right knee",
                    "left_ankle": "Left ankle",
                    "right_ankle": "Right ankle",
                    "left_toes": "Toes on left foot",
                    "right_toes": "Toes on right foot",
                },
                "required": True,
            },
        ],
    },
    {
        "id": "SN013",
        "title": "Musculoskeletal Pain",
        "clinical_area": "musculoskeletal",
        "severity_source": "muscle_pain_areas",
        "severity_method": "region_count",
        "questions": [
            {
                "id": "muscle_pain_areas",
                "type": "muscle-diagram",
                "text": "Please choose all the areas where you have experienced muscle pain since the last record.",
                "regions": {
                    # Front view
                    "left_jaw": "Left jaw",
                    "right_jaw": "Right jaw",
                    "neck": "Neck",
                    "left_chest": "Left chest",
                    "right_chest": "Right chest",
                    "abdomen": "Abdomen",
                    "left_shoulder": "Left shoulder",
                    "right_shoulder": "Right shoulder",
                    "left_bicep": "Left bicep",
                    "right_bicep": "Right bicep",
                    "left_lower_arm": "Left forearm",
                    "right_lower_arm": "Right forearm",
                    "left_quadriceps": "Left quadriceps",
                    "right_quadriceps": "Right quadriceps",
                    "left_lower_leg": "Left lower leg",
                    "right_lower_leg": "Right lower leg",
                    # Back view
                    "upper_back": "Upper back",
                    "lower_back": "Lower back",
                    "left_buttock": "Left buttock",
                    "right_buttock": "Right buttock",
                    "left_tricep": "Left tricep",
                    "right_tricep": "Right tricep",
                    "left_hamstrings": "Left hamstrings",
                    "right_hamstrings": "Right hamstrings",
                },
                "region_sides": {
                    "left_jaw": "front",
                    "right_jaw": "front",
                    "neck": "front",
                    "left_chest": "front",
                    "right_chest": "front",
                    "abdomen": "front",
                    "left_shoulder": "front",
                    "right_shoulder": "front",
                    "left_bicep": "front",
                    "right_bicep": "front",
                    "left_lower_arm": "front",
                    "right_lower_arm": "front",
                    "left_quadriceps": "front",
                    "right_quadriceps": "front",
                    "left_lower_leg": "front",
                    "right_lower_leg": "front",
                    "upper_back": "back",
                    "lower_back": "back",
                    "left_buttock": "back",
                    "right_buttock": "back",
                    "left_tricep": "back",
                    "right_tricep": "back",
                    "left_hamstrings": "back",
                    "right_hamstrings": "back",
                },
                "required": True,
            },
        ],
    },
]

# Build a flat lookup: question_id -> (section, question_def)
QUESTION_LOOKUP = {}
for _section in SECTIONS:
    for _question in _section["questions"]:
        QUESTION_LOOKUP[_question["id"]] = (_section, _question)
